### ISSUE TITLE
Password for uiiumovies - XXX?

### ISSUE THREAD

**Issue by onlytanmoy** [mrgsi/repository.dirtyg#2]
Please let me know the password to open the uiiumovies - XXX video addon installed from the Dirty-G repo?

**Comment by mrgsi** [comment]
You set that yourself after you install the program and run it. It's asks you to create a password and saves it for future use. If you accidentally set it and forgot the password, uninstall, then reinstall, set your password.

**Comment by onlytanmoy** [comment]
Thanks for the clarification mate, all good now 😊
