### ISSUE TITLE
SC19 for Kodi 21 Omega

### ISSUE THREAD

**Issue by Better-Red** [mrgsi/repository.dirtyg#4]
With Kodi 21 Omega, playback stops after a few seconds. The Red Wizard has forked SC19 for Kodi 21 Omega...

https://repo.redwizard.xyz/redwizardrepo/21omega/plugin.video.sc19/plugin.video.sc19-1.3.3a.zip

**Comment by mrgsi** [comment]
Updated. Thanks for that link, much appreciated.
