### ISSUE TITLE
plugin.video.sc19

### ISSUE THREAD

**Issue by Steha78** [mrgsi/repository.dirtyg#5]
Plugin.video.sc19-1.3.3a.zip is for KODi Omega. Dependency Inputstream FFmpeg Direct minimal 21.2.0. Installation failed. Is in the Nexus repository.dirtyg-1.4.1.

**Comment by mrgsi** [comment]
Thanks for reporting that, I didn't notice it. I assumed it was backward compatible when I got it from another developer. I removed the minimal requirement version number and it seems to be working now as tested  in both 20 and 21. It will now use the appropriate Inputstream FFmpeg Direct dependency for the Kodi version installed. A newer version, (sc19.1.3.3b.zip) is now in the repo.

**Comment by Steha78** [comment]
No problem 🙂 Works great now
